### ISSUE TITLE
Software Architecture - Assignment part 1a: something went wrong

### ISSUE THREAD

**Issue by DenBrahe** [sanderr/toledoAttachmentDownloader#1]
[link](https://p.cygnus.cc.kuleuven.be/webapps/blackboard/content/listContent.jsp?course_id=_767756_1&content_id=_19894297_1)
Error message: Something went wrong.

Could this be because the group name is not enclosed by a style tag?

**Comment by sanderr** [comment]
Yes, I believe this is the case. We need either a more generic group name lookup, or a default name should be given when this happens.
