### ISSUE TITLE
Go into subdirectories to download attachments there

### ISSUE THREAD

**Issue by sanderr** [sanderr/toledoAttachmentDownloader#7]

**Comment by DenBrahe** [comment]
What would need to be done to create this feature? (hidden iframe, changes in Page, ... )

**Comment by sanderr** [comment]
The easiest way is probably to open a hidden iframe for each subdirectory, and scrape the document contained in the iframe for attachments. This could probably be done whithin the executeScript() call in _getUnsafeResourceGroups() in Page:
- Put the scraping code in function scrape(document) within the executeScript() context. In this function: when a subdirectory is encountered: create iframe DOM object, attach it to the page's object, fetch it's document, create a promise, wait for the page in the iframe to load, scrape it by recursively calling scrape(iframeDocument), and resolve the promise.

**Comment by sanderr** [comment]
Might be I was mistaken about a simple get request not sufficing. We should try this before going for the iframe approach.

**Comment by DenBrahe** [comment]
Actually, can't we see this by examining the GET HTML response? I'll try it

**Comment by DenBrahe** [comment]
So a simple GET request works. What we have to do is: wrap getUnsafeResourceGroups inner body in a function that accepts a DOM Object, and access all resources from there (recursively).

To go in a subdirectory:
`xhr = new XMLHttpRequest();
parser = new DOMParser();
doc = parser.parseFromString(xhr.response,"text/html");`
